### PR TITLE
Add my updated PR proposition

### PR DESCRIPTION
**Pull request by Skn0tt**
The previous PR template was a bit cluttered (at least for my liking).
Also, asking people to submit a single commit only is quite an antipattern (for reasons outlined in the new PR template).

What does the rest think about it? @phlprcks @rohansaw @sspangenberg @Lasklu

### CODE REVIEW

**Comment by sspangenberg** [comment]
Looks good 👍

**Comment by rohansaw** [comment]
> The previous PR template was a bit cluttered (at least for my liking).
> Also, asking people to submit a single commit only is quite an antipattern (for reasons outlined in the new PR template).
> 
> What does the rest think about it? @phlprcks @rohansaw @sspangenberg @Lasklu

why is squashing commits an antipattern didnt find a reason for that in the PR?

**Comment by Skn0tt** [comment]
> why is squashing commits an antipattern didnt find a reason for that in the PR?

"Your PR is thoughtfully structured into distinct commits, _making it easy to review._"

This blog post goes into greater detail on the topic: https://mtlynch.io/code-review-love/ (it's really good! :D)

**Comment by rohansaw** [comment]
> > why is squashing commits an antipattern didnt find a reason for that in the PR?
> 
> "Your PR is thoughtfully structured into distinct commits, _making it easy to review._"
> 
> This blog post goes into greater detail on the topic: https://mtlynch.io/code-review-love/ (it's really good! :D)

Acutally I didnt find any contradiction to squashing commits here. Before being merged the PR is strcutured into mutliple commits and only once it is merged it will be squashed into one commit. As long as the PR-Text still is explainatory I see no problem there.

**Comment by Skn0tt** [comment]
Squashing commits during the merge is totally fine, I'm with you on that.

The previous PR encouraged you to _only submit a single commit for review_, though:

> You have only one commit (if not, squash them into one commit).

**Comment by rohansaw** [comment]
ah ok, yes thats true :)

**Review by rohansaw — APPROVED** [review]

**Review by phlprcks — APPROVED** [review]

**Review by sspangenberg — APPROVED** [review]

**Review by Lasklu — APPROVED** [review]

**Pull request merged**
